# SurfCo Configuration File - Probability-Based Penalties

# Nanoparticle properties
nanoparticle:
  radius: 35.0                    # nm - nanoparticle radius
  material: "carbonblack"         # must match MaterialSet.csv
  zeta_potential: -0.015          # V - surface potential 

# Simulation parameters
simulation:
  resolution: 0.1                 # nm² per grid cell
  iteration_limit: 100000          # maximum iterations
  equilibrium_window: 90000        # iterations for equilibrium check
  
  # Energy normalization - maps raw energies to probability range
  min_adsorption_probability: 0.6  # weakest binder
  max_adsorption_probability: 0.9  # strongest binder
  
  # Event selection ratio - what fraction of events are adsorption attempts
  adsorption_event_probability: 0.99  
  
  # Vroman effect control - coverage-dependent displacement
  max_displacement_probability: 0.6   # Maximum displacement chance at high coverage (0-1)
  coverage_threshold_for_displacement: 0.15  # Coverage % where displacement starts (0-1)
  
  # Probability-based penalty system 
  probability_penalty_per_extra_protein: 0.3  # % probability reduction per extra protein displaced
  min_displacement_probability: 0.02          # Never go below % displacement chance
  base_displacement_penalty: 0.2             # % reduction for any displacement attempt

# Protein concentrations (mg/mL)
proteins:
  HSA: 45.0      # Human Serum Albumin
  FIB-B: 3.0     # Fibrinogen B chain
  HDL: 15.0      # High-density lipoprotein
  FIB-A: 3.0     # Fibrinogen A chain